# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='/home/asmaanabil/github/website/photos/media/photos/')),
                ('features', models.FileField(blank=True, upload_to='/home/asmaanabil/github/website/photos/media/features/')),
            ],
        ),
    ]
