# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='features',
            field=models.FileField(blank=True, upload_to='/home/manar/website/photos/media/features/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='/home/manar/website/photos/media/photos/'),
        ),
    ]
