# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170219_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='/media/photos'),
        ),
    ]
