# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20170224_1358'),
        ('photos', '0003_auto_20170224_1400'),
    ]

    operations = [
    ]
