# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='features',
            field=models.FileField(blank=True, upload_to='/media/features/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='/media/photos/'),
        ),
    ]
