# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20170617_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='features',
            field=models.FileField(blank=True, upload_to='./features/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='./photos/'),
        ),
    ]
