# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20170617_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='label_name',
            field=models.ManyToManyField(to='photos.LabelsClass'),
        ),
    ]
